"use client";

import { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  ShieldAlert,
  ShieldCheck,
  ShieldHalf,
  CheckCircle2,
  Circle,
  Activity,
  ArrowRight,
  Zap,
  Lock,
  FileText
} from "lucide-react";
import Link from "next/link";
import PdfDownloadButton from "@/app/components/PdfDownloadButton";
import NotionExportButton from "@/app/components/NotionExportButton";

/* ────────────────────────────────────────────────────────
   DATA STRUCTURE
   ──────────────────────────────────────────────────────── */

const COMPLIANCE_QUESTIONS = [
  { id: "q1", text: "Is Two-Factor Authentication (2FA) enforced across all company accounts?" },
  { id: "q2", text: "Is there a documented offboarding procedure for terminated employees?" },
  { id: "q3", text: "Are vendor security assessments conducted annually?" },
  { id: "q4", text: "Do all employees complete mandatory security awareness training upon hire?" },
  { id: "q5", text: "Is sensitive customer data encrypted both in transit and at rest?" },
  { id: "q6", text: "Do you have an Incident Response Plan that is tested at least annually?" },
  { id: "q7", text: "Are access rights reviewed and revoked promptly when roles change?" },
  { id: "q8", text: "Is there a formal Disaster Recovery and Business Continuity Plan in place?" },
  { id: "q9", text: "Do you maintain an updated asset inventory for all hardware and software?" },
  { id: "q10", text: "Are system logs centrally collected, monitored, and retained for 90+ days?" },
  { id: "q11", text: "Are password policies enforced (e.g., minimum length, complexity)?" },
  { id: "q12", text: "Is there a formal change management process for deploying code to production?" },
];

/* ────────────────────────────────────────────────────────
   HELPER: GENERATE MARKDOWN REPORT
   ──────────────────────────────────────────────────────── */

function generateMarkdownReport(checkedIds: Set<string>, score: number, status: string) {
  const checkedQuestions = COMPLIANCE_QUESTIONS.filter(q => checkedIds.has(q.id));
  const uncheckedQuestions = COMPLIANCE_QUESTIONS.filter(q => !checkedIds.has(q.id));

  let md = `# Enterprise Compliance & Security Report\n\n`;
  md += `**Overall Score:** ${score}%\n`;
  md += `**Security Posture:** ${status}\n\n`;

  md += `## ❌ Critical Gaps to Remediate (${uncheckedQuestions.length})\n`;
  if (uncheckedQuestions.length === 0) {
    md += `*No critical gaps identified. Excellent work!*\n`;
  } else {
    uncheckedQuestions.forEach(q => md += `- [ ] ${q.text}\n`);
  }

  md += `\n## ✅ Compliant Areas (${checkedQuestions.length})\n`;
  if (checkedQuestions.length === 0) {
    md += `*None identified. Immediate action required.*\n`;
  } else {
    checkedQuestions.forEach(q => md += `- [x] ${q.text}\n`);
  }

  md += `\n---\n*Report generated by Template Registry. To access the full ISO-27001 Remediation Plan and 3,000+ enterprise SOPs, upgrade to Pro.*`;

  return md;
}

/* ────────────────────────────────────────────────────────
   PAGE COMPONENT
   ──────────────────────────────────────────────────────── */

export default function ScorecardClient() {
  const [checkedItems, setCheckedItems] = useState<Set<string>>(new Set());

  const handleToggle = (id: string) => {
    const next = new Set(checkedItems);
    if (next.has(id)) {
      next.delete(id);
    } else {
      next.add(id);
    }
    setCheckedItems(next);
  };

  const total = COMPLIANCE_QUESTIONS.length;
  const checkedCount = checkedItems.size;
  const score = Math.round((checkedCount / total) * 100);

  const { status, color, icon: StatusIcon, description } = useMemo(() => {
    if (score === 100) {
      return {
        status: "Audit Ready",
        color: "text-emerald-400",
        icon: ShieldCheck,
        description: "Excellent. Your operations align with enterprise security standards."
      };
    }
    if (score >= 50) {
      return {
        status: "Vulnerable",
        color: "text-amber-400",
        icon: ShieldHalf,
        description: "Moderate risk. You have foundational security, but critical gaps remain."
      };
    }
    return {
      status: "High Risk",
      color: "text-rose-400",
      icon: ShieldAlert,
      description: "Severe vulnerabilities detected. Immediate remediation is required."
    };
  }, [score]);

  const markdownReport = useMemo(() => generateMarkdownReport(checkedItems, score, status), [checkedItems, score, status]);
  const pdfTitle = `Compliance_Scorecard_${score}Percent`;

  return (
    <div className="min-h-screen bg-[#0A0A0F] text-white selection:bg-indigo-500/30 selection:text-white">
      {/* ── AMBIENT BACKGROUND ── */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden z-0">
        <div className="absolute top-[-20%] right-[-10%] w-[600px] h-[600px] bg-indigo-600/10 rounded-full blur-[150px]" />
        <div className="absolute bottom-[10%] left-[-10%] w-[500px] h-[500px] bg-rose-600/5 rounded-full blur-[130px]" />
      </div>

      <main className="relative z-10 max-w-4xl mx-auto px-6 pt-16 pb-32">
        {/* ── HERO HEADER ── */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-center mb-14"
        >
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white/5 border border-white/10 text-[13px] font-medium text-gray-400 mb-8 backdrop-blur-sm">
            <Activity className="w-3.5 h-3.5 text-indigo-400" />
            Interactive Assessment
          </div>

          <h1 className="font-serif text-5xl md:text-6xl tracking-tight leading-[1.1] mb-6">
            Compliance & Security{" "}
            <span className="bg-gradient-to-r from-indigo-400 via-purple-400 to-indigo-400 bg-clip-text text-transparent">
              Scorecard
            </span>
          </h1>

          <p className="text-lg text-gray-400 max-w-2xl mx-auto leading-relaxed">
            Evaluate your operational health against enterprise standards. Identify gaps, 
            calculate your risk profile, and generate a remediation plan instantly.
          </p>
        </motion.div>

        {/* ── STICKY PROGRESS BAR ── */}
        <motion.div 
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="sticky top-4 z-50 mb-12"
        >
          <div className="bg-[#111827]/80 backdrop-blur-xl border border-white/10 rounded-2xl p-6 shadow-2xl shadow-black/50">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-4">
              <div>
                <h2 className="text-sm font-semibold text-gray-300 uppercase tracking-widest mb-1">Company Health Score</h2>
                <div className="flex items-center gap-3">
                  <StatusIcon className={`w-6 h-6 ${color}`} />
                  <span className={`text-2xl font-bold ${color}`}>{score}%</span>
                  <span className="text-lg text-gray-400 font-medium">— {status}</span>
                </div>
              </div>
              <div className="text-right">
                <p className="text-sm text-gray-400">{checkedCount} of {total} requirements met</p>
              </div>
            </div>
            
            {/* Progress Track */}
            <div className="h-3 w-full bg-white/5 rounded-full overflow-hidden">
              <motion.div 
                className={`h-full rounded-full bg-gradient-to-r ${score >= 80 ? 'from-emerald-500 to-emerald-400' : score >= 50 ? 'from-amber-500 to-amber-400' : 'from-rose-500 to-rose-400'}`}
                initial={{ width: 0 }}
                animate={{ width: `${score}%` }}
                transition={{ duration: 0.5, ease: "easeOut" }}
              />
            </div>
          </div>
        </motion.div>

        {/* ── CHECKLIST ── */}
        <div className="space-y-4 mb-16">
          {COMPLIANCE_QUESTIONS.map((q, idx) => {
            const isChecked = checkedItems.has(q.id);
            return (
              <motion.div
                key={q.id}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: idx * 0.05 + 0.3 }}
                onClick={() => handleToggle(q.id)}
                className={`group relative flex items-start gap-4 p-5 rounded-2xl border transition-all duration-200 cursor-pointer ${
                  isChecked 
                    ? "bg-indigo-500/10 border-indigo-500/30" 
                    : "bg-white/[0.02] border-white/10 hover:bg-white/[0.04] hover:border-white/20"
                }`}
              >
                <div className="mt-0.5 shrink-0">
                  <AnimatePresence mode="wait">
                    {isChecked ? (
                      <motion.div
                        key="checked"
                        initial={{ scale: 0, opacity: 0 }}
                        animate={{ scale: 1, opacity: 1 }}
                        exit={{ scale: 0, opacity: 0 }}
                        transition={{ duration: 0.2 }}
                      >
                        <CheckCircle2 className="w-6 h-6 text-indigo-400" />
                      </motion.div>
                    ) : (
                      <motion.div
                        key="unchecked"
                        initial={{ scale: 0, opacity: 0 }}
                        animate={{ scale: 1, opacity: 1 }}
                        exit={{ scale: 0, opacity: 0 }}
                        transition={{ duration: 0.2 }}
                      >
                        <Circle className="w-6 h-6 text-gray-600 group-hover:text-gray-400 transition-colors" />
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
                <p className={`text-base md:text-lg leading-relaxed transition-colors duration-200 ${
                  isChecked ? "text-indigo-100" : "text-gray-300 group-hover:text-gray-200"
                }`}>
                  {q.text}
                </p>
              </motion.div>
            );
          })}
        </div>

        {/* ── INVISIBLE CONTENT FOR PDF EXPORT ── */}
        {/* We use id="pdf-content" to allow the PdfDownloadButton to capture it */}
        <div id="pdf-content" className="hidden print:block absolute -left-[9999px] top-0 p-12 bg-white text-black w-[800px]">
           <div className="flex justify-between items-end border-b-2 border-[#F3F4F6] pb-8 mb-12">
            <div className="flex items-center gap-3">
              <span className="font-serif text-2xl text-[#111827] tracking-tight">
                Template Registry
              </span>
            </div>
            <div className="text-right">
              <p className="text-[10px] font-bold text-[#9CA3AF] uppercase tracking-[0.25em] leading-none mb-2">
                Compliance Report
              </p>
              <p className="text-[10px] text-[#D1D5DB] uppercase tracking-widest leading-none">
                Score: {score}%
              </p>
            </div>
          </div>
          
          <h1 className="text-3xl font-bold mb-6">Security Posture: {status}</h1>
          <p className="text-lg mb-8 text-gray-700">{description}</p>
          
          <h2 className="text-xl font-bold mb-4 border-b pb-2">Critical Gaps ({total - checkedCount})</h2>
          <ul className="mb-8 space-y-3">
            {COMPLIANCE_QUESTIONS.filter(q => !checkedItems.has(q.id)).map(q => (
              <li key={q.id} className="flex gap-3 text-gray-800">
                <span className="font-bold text-red-500">✗</span> {q.text}
              </li>
            ))}
          </ul>

          <h2 className="text-xl font-bold mb-4 border-b pb-2">Compliant Areas ({checkedCount})</h2>
          <ul className="space-y-3">
            {COMPLIANCE_QUESTIONS.filter(q => checkedItems.has(q.id)).map(q => (
              <li key={q.id} className="flex gap-3 text-gray-800">
                <span className="font-bold text-green-500">✓</span> {q.text}
              </li>
            ))}
          </ul>
        </div>

        {/* ── PAYWALL / RESULTS SECTION ── */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="relative rounded-3xl bg-white/[0.03] border border-white/10 backdrop-blur-xl p-8 md:p-12 overflow-hidden"
        >
          {/* Decorative glow based on score */}
          <div className={`absolute top-0 right-0 w-[400px] h-[400px] rounded-full blur-[120px] opacity-20 pointer-events-none ${
            score >= 80 ? 'bg-emerald-500' : score >= 50 ? 'bg-amber-500' : 'bg-rose-500'
          }`} />

          <div className="relative z-10 text-center max-w-2xl mx-auto">
            <div className="w-16 h-16 rounded-2xl bg-white/5 flex items-center justify-center mx-auto mb-6 border border-white/10">
              <Lock className="w-8 h-8 text-gray-300" />
            </div>

            <h2 className="text-2xl md:text-3xl font-bold text-white mb-4">
              {score < 100 ? "You have identified gaps in your operational security." : "Your baseline is strong, but compliance requires continuous enforcement."}
            </h2>
            <p className="text-gray-400 text-lg mb-8">
              {score < 100 ? "Fix them instantly." : "Standardize your excellence."} Unlock Lifetime Access to export your full ISO-27001 Remediation Plan and our library of 3,000+ enterprise SOPs.
            </p>

            <div className="flex flex-col sm:flex-row justify-center items-center gap-4 mb-10">
               <a
                href="https://buy.polar.sh/polar_cl_SvXvG4jukzotDEekGNPrlidHn7MXXdXlQJSeT2Kt33l?success_url=https://templateregistry.com/success"
                className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-8 py-4 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-xl font-bold text-sm hover:from-indigo-500 hover:to-purple-500 transition-all shadow-lg shadow-indigo-500/25 hover:shadow-indigo-500/40 hover:scale-[1.02] active:scale-[0.98]"
              >
                <Zap className="w-4 h-4" />
                Unlock All-Access — $14.99
              </a>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 max-w-lg mx-auto">
              <PdfDownloadButton title={pdfTitle} requireEmailGate={true} />
              <NotionExportButton markdownContent={markdownReport} />
            </div>

            <div className="mt-8 pt-8 border-t border-white/10 text-sm text-gray-500">
              Export functionality requires a Pro membership. Download an actionable breakdown of your {score}% score directly to PDF or Notion.
            </div>
          </div>
        </motion.div>
      </main>

      {/* ── JSON-LD SCHEMA ── */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebApplication",
            "name": "Interactive Compliance Risk Scorecard | Template Registry",
            "applicationCategory": "BusinessApplication",
            "operatingSystem": "All",
            "description": "Calculate your company's operational compliance risk score. Instantly evaluate your business against enterprise security standards.",
            "offers": {
              "@type": "Offer",
              "price": "0",
              "priceCurrency": "USD"
            }
          })
        }}
      />
    </div>
  );
}
